name: Publish to PyPI
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: fetch code
        uses: actions/checkout@v3

      - name: get nox
        uses: excitedleigh/setup-nox@v2.1.0

      - name: flit publish
        run: nox -s publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
