name: Bump PyPI requirements
on:
  schedule:
    - cron: '53 8 * * *'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: fetch code (develop) and zpy submodule
        uses: actions/checkout@v2
        with:
          ref: develop
          submodules: recursive

      - name: install tools from distro repo
        run: sudo apt -yqq --no-install-recommends install ca-certificates zsh
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: get nox
        uses: excitedleigh/setup-nox@v2.0.0

      - name: upgrade lockfiles
        run: nox -s lock

      - name: push any changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am 'Bump PyPI requirements [Automated]' && git push || true
