name: Bump PyPI requirements
on:
  schedule:
    - cron: '53 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: fetch code (develop) and zpy submodule
        uses: actions/checkout@v2
        with:
          ref: develop
          submodules: recursive

      - name: install tools from distro repo
        run: sudo apt -yqq --no-install-recommends install ca-certificates zsh
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: configure Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: upgrade lockfiles
        run: ./mk/reqs.zsh

      - name: push any changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am 'Bump PyPI requirements [Automated]' && git push || true
