name: Run tests
on:
  push
jobs:

  tests:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:

      - name: fetch code
        uses: actions/checkout@v4

      - name: install Python 3.7 on Windows
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - uses: jdx/mise-action@v2

      - name: run tests
        run: |
          mise run test
          mise run test-without-toml
          mise run combine-coverage
        env:
          PYTHONIOENCODING: utf-8

      - name: upload coverage data
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.json
          token: ${{ secrets.CODECOV_TOKEN }}
